import os

class Config:
    SLACK_PORTFOLIO_WEBHOOK = os.getenv("SLACK_PORTFOLIO_WEBHOOK")
    RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY")
    GITHUB_WEBHOOK_SECRET = os.getenv("GITHUB_WEBHOOK_SECRET")